secrets: secrets.yml

templates:

  global:
    disable_builtins:
      - seen
      - seen_info_hash
    disable_plugin:
      - seen_movies

tasks:

  _test:
    mock:
      - { title: "x", tvdb_id: 176941 }
      - { title: "x", tvdb_id: 276312 }
      - { title: "x", tvdb_id: 273351 }
      - { title: "x", tvdb_id: 264991 }
    accept_all: yes
    thetvdb_add:
    # thetvdb_remove:
      account_id: '{{ secrets.tv.aid }}'

